<!DOCTYPE html>
<html lang="en">
	<head>
  		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="">
		<meta name="author" content="">

  		<title><?= $pageTitle; ?></title>

		<!-- Bootstrap core CSS -->
		<link href="<?= HOST; ?>../Web/Ressources/bootstrap/css/bootstrap.min.css" rel="stylesheet">

		<!-- Custom fonts for this template -->
		<link href="<?= HOST; ?>../Web/Ressources/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
		<link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
		
		<!-- *** -->
 		<link rel="stylesheet" type="text/css" href="<?= HOST; ?>../Web/Ressources/css/style.css">
 		<!-- Custom styles for this template -->
		<link href="<?= HOST; ?>../Web/Ressources/css/agency.min.css" rel="stylesheet">

 		<!-- Bootstrap core JavaScript -->
		<script src="<?= HOST; ?>../Web/Ressources/jquery/jquery3.4.1.min.js"></script>
		<script src="<?= HOST; ?>../Web/Ressources/bootstrap/js/bootstrap.bundle.min.js"></script>
		<script src="<?= HOST; ?>../Web/Ressources/bootstrap/js/bootstrap.min.js"></script>
		<script src="<?= HOST; ?>../Web/Ressources/bootstrap/js/Chart.min.js"></script>

		<script src="https://unpkg.com/popper.js@1"></script>
		<script src="https://unpkg.com/tippy.js@5"></script>
  		<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

		<!-- Plugin JavaScript -->
		<script src="<?= HOST; ?>../Web/Ressources/jquery-easing/jquery.easing.min.js"></script>

		<script src="<?= HOST; ?>../Web/Ressources/js/jqBootstrapValidation.js"></script>
  		<script src="<?= HOST; ?>../Web/Ressources/js/filter.js"></script>  

		<!-- Custom scripts for this template -->
		<!-- <script src="<?= HOST; ?>../Web/Ressources/js/agency.min.js"></script> -->

	</head>
	<body>
	<!-- Navigation -->
	  	<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
		    <div class="container">
		      <a class="navbar-brand js-scroll-trigger" href="<?= HOST;?>accueil">Human Cart'Office</a>
		      <div class="collapse navbar-collapse" id="navbarResponsive">
		        <ul class="navbar-nav text-uppercase ml-auto">
		          	<li class="nav-item">
		            	<a class="nav-link js-scroll-trigger" href="<?= HOST;?>accueil">Accueil</a>
		          	</li>
		          	<li class="nav-item">
		            	<a class="nav-link js-scroll-trigger" href="<?= HOST;?>a-propos">A propos</a>
		          	</li>
		          	<?php if (!isset($_SESSION['compte']) || $_SESSION['compte']['identifiant'] == "candidat"): ?>
		          		<li class="nav-item">
			            	<a class="nav-link js-scroll-trigger" href="<?= HOST;?>offres">Emploi</a>
			          	</li>	
		          	<?php endif ?>
		          	<li class="nav-item">
		            	<a class="nav-link js-scroll-trigger" href="<?= HOST;?>contact">Contact</a>
		          	</li>
		          	<?php if (isset($_SESSION['compte'])): ?>
		          	<li class="nav-item">
		            	<a class="nav-link js-scroll-trigger" href="<?= HOST;?>deconnexion">Deconnexion</a>
		          	</li>
		          	<li class="nav-item">
		            	<a class="nav-link js-scroll-trigger" href="<?= HOST;?>manage/<?= $_SESSION['compte']['identifiant']; ?>/dashboard">		            		
		            		Mon compte
		            		<img class="rounded-circle" src="
		            			<?php 
		            				if($_SESSION['compte']['identifiant'] == "entreprise") {
		            					if ($_SESSION['user']['logo'] != "") {
		            						echo HOST ."../Web/Ressources/images/" . $_SESSION['compte']['identifiant'] . "s/" . $_SESSION['user']['logo'];
		            					}
		            				} else {
		            					if ($_SESSION['user']['photo'] != "") {
		            						echo HOST ."../Web/Ressources/images/" . $_SESSION['compte']['identifiant'] . "s/" . $_SESSION['user']['photo'];
		            					}
		            				}
		            			?>
		                    " id="profilImage">
		            	</a>
		          	</li>
		          	<?php else : ?>
		          	<li class="nav-list nav-item">
		            	<a class="nav-link js-scroll-trigger" href="#">S'inscrire</a>
	                	<ul class="list text-lowercase">
	                    	<li><a href="<?= HOST; ?>create-compte?identifiant=candidat">Candidat</a></li>
	                    	<li><a href="<?= HOST; ?>create-compte?identifiant=entreprise">Entreprise</a></li>
	                	</ul>
		          	</li>
		          	<li class="nav-item">
		            	<a class="nav-link js-scroll-trigger" href="<?= HOST;?>connexion">Se connecter</a>
		          	</li>
		          	<?php endif ?>
		        </ul>
		      </div>

		    </div>
	  	</nav>
		<div id="body">
		<?php if (isset($_SESSION['compte']) && $_SESSION['isBackOffice']):?>
			<div class="row">
				<div class="col-lg-2 col-md-3">
					<?php if ($_SESSION['compte']['identifiant'] == "superadmin") {
							include_once(__DIR__ . '/../App/Backend/Templates/menuAdmin.phtml');
						} else if ($_SESSION['compte']['identifiant'] == "entreprise") {
							include_once(__DIR__ . '/../App/Backend/Templates/menuEntreprise.phtml');
						} else if ($_SESSION['compte']['identifiant'] == "candidat") {
							include_once(__DIR__ . '/../App/Backend/Templates/menuCandidat.phtml');
						}
		    		?>
				</div>			
				<div class="col-lg-10 col-md-9 scrollable">
					<?= $pageContent; ?>
				</div>
			</div>
		<?php else : ?>
			<div class="scrollable">
				<?= $pageContent; ?>
			</div>
		<?php endif; ?>			    	
	    	
    	<?php
	    	if (isset($_SESSION['info'])) {
	   			foreach ($_SESSION['info'] as $type => $message) {
					echo "<div class='container alert alert-" . $type . "' data-dismiss='alert' id='alert'>" . $message . "</div>";
					unset($_SESSION['info']);		
				}
	    	}
	    	//Test
	    	/*if (isset($_SESSION['variable'])) {
	    		echo "<pre>";
				var_dump($_SESSION['variable']);
	    	}*/
	    	//fin Test
	    ?>
	    	
		</div>	
	 <!-- Footer -->
		<footer class="footer">
		    <div class="container-fluid">
		      	<div class="row align-items-left">
			        <div class="col-md-4">
			          	<span class="copyright">Copyright &copy; Your Website 2019</span>
			        </div>
			        <div class="col-md-3" id="navigation-rapide">
			        	<h5>NAVIGATION RAPIDE</h5>
		        		<p>
			            	<a href="<?= HOST;?>a-propos">A propos</a>
			          	</p>
			          	<p>
			            	<a href="<?= HOST;?>offres">Emploi</a>
			          	</p>
			          	<p>
			            	<a href="<?= HOST;?>contact">Contact</a>
			          	</p>
			        </div>
			        <div class="col-md-3" id="adresse">
		        		<h4>Human Cart'Office</h4>
		        		
		        	</div>
		      	</div>
		    </div>
		</footer> 
	</body>
</html>

<script src="<?= HOST; ?>../Web/Ressources/js/header.js"></script>
